### PR TITLE
port delete node changes from jsx

### PR DESCRIPTION
**Pull request by ahsayde**
https://github.com/threefoldtech/js-sdk/issues/355

### CODE REVIEW

**Comment by ahsayde** [comment]
to test this changes

- start threebot and make sure the old package is deleted
```
JS-NG> server = j.servers.threebot.get('default')
```
remove the package in case it is installed using giturl
```
JS-NG> threebot.packages.delete("farmmanagement")
```

re add the package again using the path
```
JS-NG> threebot.packages.add(path="/sandbox/code/github/js-next/js-sdk/jumpscale/packages/farmmanagement")
```

**Comment by zaibon** [comment]
I tried to test it, when I click the delete button I receive an error: 
2020-07-29_1610x330_scrot

**Comment by ahsayde** [comment]
please make sure to stop the server, exit the shell and starting it again after pulling the latest code

**Comment by ahsayde** [comment]
@zaibon can u verify again ?

**Comment by zaibon** [comment]
2020-08-07_829x281_scrot

**Comment by m-motawea** [comment]
@zaibon I hardcoded the owner_id and it should be working now. can you try again?
image

**Review by rkhamis — APPROVED** [review]

**Pull request merged**
